FROM debian:bullseye-slim
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -yq && apt-get install -yq software-properties-common \
    wget gpg 
RUN apt-get install -yq locales apt-utils
RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    dpkg-reconfigure locales && \
    update-locale LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

## add multiple php repository
RUN sh -c 'echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list' 
RUN wget -qO - https://packages.sury.org/php/apt.gpg | apt-key add - 
RUN apt-get update -yq && apt-get dist-upgrade -yq

## install php
RUN apt-get update -yq && apt-get install -yq php7.3 php7.3-fpm php7.3-common php7.3-mysql php7.3-gmp \
    php7.3-curl php7.3-intl php7.3-mbstring php7.3-xmlrpc php7.3-gd \
    php7.3-xml php7.3-cli php7.3-zip php7.3-soap php7.3-common php-imagick php7.3-pgsql \
    php7.3-xml php7.3-bcmath php7.3-json php-redis zip php-geoip imagemagick

## set php version
RUN update-alternatives --set php /usr/bin/php7.3

## install Composer
RUN wget -O -  https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

## install nodejs
RUN wget -O - https://deb.nodesource.com/setup_lts.x | bash - &&\
    apt-get install -yq nodejs

RUN npm install --global yarn
RUN npm install -g npm@9.8.1

RUN wget -q -O - https://nginx.org/keys/nginx_signing.key | gpg --dearmor | tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null
RUN apt-get update -yq && apt-get install nginx-extras -yq
COPY ./entry-point.sh /app/entry-point.sh
RUN chmod +x /app/entry-point.sh
