version: '3'

networks:
  db:
    driver: bridge
services:
  php73:
    container_name: docker-php-73
    build:
      context: .
      dockerfile: Dockerfile.73
    env_file:
       - .env
    hostname: docker-php-73
    ports:
       - "8073:80"
    entrypoint: /root/entry-point.sh
    volumes:
      - ${WORKING_DIR}:${DOCUMENT_ROOT}
    working_dir: ${DOCUMENT_ROOT}
    networks:
      db:

  php82:
      container_name: docker-php-82
      build:
        context: .
        dockerfile: Dockerfile.82
      hostname: docker-php-82
      env_file:
        - .env
      ports:
         - "8082:80"
      entrypoint: /root/entry-point.sh
      volumes:
        - ${WORKING_DIR}:/var/www/html
      working_dir: ${DOCUMENT_ROOT}
      networks:
        db:

  mariadb:
        image: "mariadb:latest"
        restart: always
        environment:
          MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD}"
        ports:
            - 3306:3306
        networks:
            db:
  phpmyadmin:
          image: "phpmyadmin:latest"
          restart: unless-stopped
          environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mariadb
            - PMA_PORT=3306
          ports:
            - 8080:80
          networks:
            db:
