version: '3'

services:
  php73:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.73
    hostname: docker-php
    ports:
       - "8073:80"
    entrypoint: /app/entry-point.sh
    volumes:
      - ./php73:/var/www/html
    working_dir: /app
