#!/bin/sh
# Run Composer inside a PHP container.
# Target another container: PHP_CONTAINER=docker-php-73 scripts/composer install
container="${PHP_CONTAINER:-docker-php-82}"
exec docker exec -i "$container" composer "$@"
